event: payment_authorized
method_distribution:
  netbanking: 2
  card: 4
  upi: 3
  wallet: 1
enum_fields:      
  - path: bank
    values: [HDFC, SBI, CITI]
  - path: wallet
    values: [PAYTM, FREECHARGE]
  - path: psp
    values: [okhdfcbank, oksbi, upi, paytm]
range_fields:
   - path: amount
     min: 10000
     max: 50000
