netbanking:
  weight: 2
  fields:
    - path: payload.payment.entity.bank
      values: ["HDFC", "SBI", "CITI"]
card:
  weight: 3
  fields:
    - path: payload.payment.entity.card.network
      values: ["Visa", "Rupay", "Mastercard"]
  fields:
    - path: payload.payment.entity.card.type
      values: ["credit", "debit"]
wallet:
  weight: 2
  fields:
    - path: payload.payment.entity.wallet
      values: ["paytm", "freecharge"]
upi:
  weight: 3
  fields:
    - path: payload.payment.entity.vpa
      values: ["test@okhdfcbank", "test@oksbi", "test@upi", "test@paytm"]
range_fields:
  - path: payload.payment.entity.amount
    min: 10000
    max: 50000
