{
 "title": "Razorpay metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Payment counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "payment_authorized",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Payment counts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "payment_authorized",
     "query": "SELECT count(\"amount\") FROM \"payment_authorized\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "payment_failed",
     "query": "SELECT count(\"amount\") FROM \"payment_failed\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Payment volume",
   "type": "graph",
   "description": "Payment volume over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "payment_authorized",
     "query": "SELECT sum(\"amount\")/100 FROM \"payment_authorized\" WHERE $timeFilter GROUP BY time($__interval), \"method\" fill(null)",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Payment methods",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "payment_authorized",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Debit cards vs credit cards",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "cardType" ], "type": "tag" }
     ],
     "measurement": "payment_authorized",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "card" }
     ]
    }
   ]
  },
  {
   "title": "Top PSPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "upiPsp" ], "type": "tag" }
     ],
     "measurement": "payment_authorized",
     "query": "SELECT top(count(\"amount\")) FROM \"payment_authorized\" WHERE $timeFilter GROUP BY \"upiPsp\"",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "upi" }
     ]
    }
   ]
  },
  {
   "title": "Top Netbanking banks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "bank" ], "type": "tag" }
     ],
     "measurement": "payment_authorized",
     "query": "SELECT top(count(\"amount\")) FROM \"payment_authorized\" WHERE $timeFilter GROUP BY \"upiPsp\"",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "netbanking" }
     ]
    }
   ]
  }
 ]
}